---
- name: Install and start the latest Apache HTTPD package on the pre-production web servers hosts
  hosts: pre_prod_web_servers
  become: yes
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true

- name: Install and start Apache HTTPD package on the production web servers hosts
  hosts: prod_web_servers
  become: yes
  tasks:
    - name: httpd package is present
      yum:
        name: httpd-2.4.37-10.module+el8+2764+7127e69e
        state: present
    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
